version: "3.8"

services:
  yansir-whatsapp:
    image: yansircc/yansir-whatsapp:latest
    container_name: yansir-whatsapp
    ports:
      - "3000:3000"
    networks:
      - yansir-network

  waha:
    image: devlikeapro/waha-plus:arm
    container_name: waha
    environment:
      WAHA_DASHBOARD_ENABLED: false
    ports:
      - "3002:3000"
    networks:
      - yansir-network

networks:
  yansir-network:
    driver: bridge
